{{ if or .Values.service.http .Values.service.grpc }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    service: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}
  ports:
    {{ if .Values.service.http }}
    - name: http
      port: 3000
      targetPort: 3000
    {{ end }}

    {{ if .Values.service.grpc }}
    - name: grpc
      port: 4000
      targetPort: 4000
    {{ end }}
{{ end }}
