name: Deploy Go app

on:
  workflow_call:

env:
  BASE_DOMAIN: emitra.co

jobs:
  k8s:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout actions repository
        uses: actions/checkout@v4
        with:
          repository: ukasyah-lab/actions
          ref: main
          token: ${{ secrets.PAT_REPO }}
          path: actions

      - name: ZeroTier
        uses: zerotier/github-action@v1.0.1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}

      - name: Get app name
        id: app-name
        uses: MariachiBear/get-repo-name-action@v1.3.0

      - name: Get app version
        id: app-version
        uses: mikefarah/yq@master
        with:
          cmd: yq '.version' 'actions.yaml'

      - name: Get subdomain
        id: subdomain
        uses: mikefarah/yq@master
        with:
          cmd: yq '.deploy.subdomain' 'actions.yaml'

      - uses: azure/setup-helm@v4

      - name: Create ~/.kube/config file
        run: |
          mkdir -p /home/runner/.kube
          echo "${{ secrets.KUBECONFIG }}" >> /home/runner/.kube/config

      - name: Create Chart.yaml file
        run: |
          export APP_NAME="${{ steps.app-name.outputs.repository-name }}"
          export APP_VERSION="${{ steps.app-version.outputs.result }}"
          envsubst < actions/.helm/Chart.template.yaml > actions/.helm/Chart.yaml

      - name: Deploy to development
        run: |
          ingressHost=""

          if [ "${{ steps.subdomain.outputs.result }}" != "null" ]; then
            ingressHost="${{ steps.subdomain.outputs.result }}.dev.${{ env.BASE_DOMAIN }}"
          fi

          helm upgrade --install --history-max=1 \
            -n development -f actions.yaml \
            --set image.tag="main" \
            --set deploy.ingress.host="$ingressHost" \
            ${{ steps.app-name.outputs.repository-name }} \
            actions/.helm

      - name: Deploy to test
        run: |
          ingressHost=""

          if [ "${{ steps.subdomain.outputs.result }}" != "null" ]; then
            ingressHost="${{ steps.subdomain.outputs.result }}.test.${{ env.BASE_DOMAIN }}"
          fi

          helm upgrade --install --history-max=1 \
            -n test -f actions.yaml \
            --set image.tag="main" \
            --set deploy.ingress.host="$ingressHost" \
            ${{ steps.app-name.outputs.repository-name }} \
            actions/.helm
