name: Deploy Docker container

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  docker-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Set environment PREFIX
        run: |
          if [ "${{ github.event.inputs.environment }}" == "development" ]; then
            echo "PREFIX=DEV" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.environment }}" == "test" ]; then
            echo "PREFIX=TEST" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.environment }}" == "staging" ]; then
            echo "PREFIX=STAG" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.environment }}" == "production" ]; then
            echo "PREFIX=PROD" >> $GITHUB_ENV
          fi

      - name: Recreate docker container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets[format('{0}_SSH_HOST', env.PREFIX)] }}
          port: ${{ secrets[format('{0}_SSH_PORT', env.PREFIX)] }}
          username: ${{ secrets[format('{0}_SSH_USERNAME', env.PREFIX)] }}
          key: ${{ secrets[format('{0}_SSH_PRIVATE_KEY', env.PREFIX)] }}
          script: |
            containerName="${{ github.event.repository.name }}"
            imageName="ghcr.io/${{ github.repository }}:main"
            envFile="containers/${containerName}/.env"

            docker rm -f $containerName
            docker pull $imageName

            if [ -f $envFile ]; then
              echo "Deploying with env file: $envFile"

              docker run -d \
                --name $containerName \
                --network main \
                --restart unless-stopped \
                --env-file $envFile \
                $imageName
            else
              echo "$envFile not found, ignoring"

              docker run -d \
                --name $containerName \
                --network main \
                --restart unless-stopped \
                $imageName
            fi

            docker image prune -f
