name: Deploy to Kubernetes

on:
  workflow_call:
    inputs:
      host:
        type: string
      http:
        type: boolean
        default: true
      grpc:
        type: boolean
        default: false

jobs:
  kubernetes:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout actions repository
        uses: actions/checkout@v4
        with:
          repository: emitra-labs/actions
          ref: main
          token: ${{ secrets.PAT_REPO }}
          path: actions

      - name: ZeroTier
        uses: zerotier/github-action@v1.0.3
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}

      - name: Get app name
        id: app-name
        uses: MariachiBear/get-repo-name-action@v1.3.0

      - name: Get app version
        id: app-version
        uses: mikefarah/yq@master
        with:
          cmd: yq -r .version package.json

      - uses: azure/setup-helm@v4

      - name: Create ~/.kube/config file
        run: |
          mkdir -p /home/runner/.kube
          echo "${{ secrets.KUBECONFIG }}" >> /home/runner/.kube/config

      - name: Create Chart.yaml file
        run: |
          export APP_NAME="${{ steps.app-name.outputs.repository-name }}"
          export APP_VERSION="${{ steps.app-version.outputs.result }}"
          envsubst < actions/.helm/Chart.template.yaml > actions/.helm/Chart.yaml

      - name: Create values.yaml file
        run: |
          cat <<EOT >> ${{ github.workspace }}/actions/.helm/values.yaml
          ${{ vars.HELM_VALUES }}
          EOT

      - name: Deploy to default namespace
        run: |
          helm upgrade --install --history-max=1 \
            --set image.tag="main" \
            --set ingress.host="${{ inputs.host }}" \
            --set service.http=${{ inputs.http && 'true' || 'false' }} \
            --set service.grpc=${{ inputs.grpc && 'true' || 'false' }} \
            ${{ steps.app-name.outputs.repository-name }} \
            actions/.helm
