name: Deploy Docker container

on:
  workflow_call:
    inputs:
      group:
        required: true
        type: string

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: ZeroTier
        uses: zerotier/github-action@v1.0.3
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restart docker container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          timeout: 1m
          script: |
            projectDir="containers/${{ inputs.group }}/${{ github.event.repository.name }}"

            if [ -d $projectDir ]; then
              cd $projectDir
              docker compose pull
              docker compose up -d
              docker image prune -f
            fi
