name: Deploy Docker container

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  docker-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Set environment PREFIX
        run: |
          if [ "${{ inputs.environment }}" == "development" ]; then
            echo "PREFIX=DEV" >> $GITHUB_ENV
          elif [ "${{ inputs.environment }}" == "test" ]; then
            echo "PREFIX=TEST" >> $GITHUB_ENV
          elif [ "${{ inputs.environment }}" == "staging" ]; then
            echo "PREFIX=STAG" >> $GITHUB_ENV
          elif [ "${{ inputs.environment }}" == "production" ]; then
            echo "PREFIX=PROD" >> $GITHUB_ENV
          fi

      - name: Recreate docker container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets[format('{0}_SSH_HOST', env.PREFIX)] }}
          port: ${{ secrets[format('{0}_SSH_PORT', env.PREFIX)] }}
          username: ${{ secrets[format('{0}_SSH_USERNAME', env.PREFIX)] }}
          key: ${{ secrets[format('{0}_SSH_PRIVATE_KEY', env.PREFIX)] }}
          script: |
            containerName="${{ github.event.repository.name }}"

            cd containers/${containerName}

            docker compose pull
            docker compose up -d
            docker image prune -f
