name: Deploy to Kubernetes

on:
  workflow_call:

jobs:
  kubernetes:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Determine deployment environment from context
        run: |
          # By default, deploy to development environment
          echo "DEPLOYMENT_ENV=development" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout actions repository
        uses: actions/checkout@v4
        with:
          repository: emitra-labs/actions
          ref: main
          path: actions

      - name: Setup ZeroTier for development environment
        uses: zerotier/github-action@v1.0.3
        if: $DEPLOYMENT_ENV == "development"
        with:
          network_id: ${{ secrets.DEV_ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.DEV_ZEROTIER_CENTRAL_TOKEN }}

      - name: Get app name
        id: app-name
        uses: MariachiBear/get-repo-name-action@v1.3.0

      - name: Get app version
        id: app-version
        uses: mikefarah/yq@master
        with:
          cmd: yq -r .version package.json

      - uses: azure/setup-helm@v4

      - name: Create ~/.kube/config file
        run: |
          mkdir -p /home/runner/.kube
          if [[ $DEPLOYMENT_ENV == "development" ]]; then
            echo "${{ secrets.DEV_KUBE_CONFIG }}" >> /home/runner/.kube/config
          fi
          chmod 600 /home/runner/.kube/config

      - name: Create Chart.yaml file
        run: |
          export APP_NAME="${{ steps.app-name.outputs.repository-name }}"
          export APP_VERSION="${{ steps.app-version.outputs.result }}"
          envsubst < actions/.helm/Chart.template.yaml > actions/.helm/Chart.yaml

      - name: Create values.yaml file
        run: |
          cat <<EOT >> ${{ github.workspace }}/actions/.helm/custom-values.yaml
          ${{ vars.HELM_VALUES }}
          EOT

      - name: Deploy to default namespace
        run: |
          helm upgrade --install --history-max=1 \
            -f actions/.helm/default-values.yaml \
            -f actions/.helm/custom-values.yaml \
            ${{ steps.app-name.outputs.repository-name }} \
            actions/.helm
