name: Test Go app

on:
  workflow_call:
    inputs:
      maildev:
        type: boolean
      postgresql:
        type: boolean
      rabbitmq:
        type: boolean

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.22.5'

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.30.1'

      - name: ZeroTier
        uses: zerotier/github-action@v1.0.3
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}

      - name: Create ~/.kube/config file
        run: |
          mkdir -p /home/runner/.kube
          echo "${{ secrets.KUBECONFIG }}" >> /home/runner/.kube/config

      - name: Expose Maildev service
        if: inputs.maildev
        run: kubectl port-forward svc/maildev 1025:1025 &

      - name: Expose PostgreSQL service
        if: inputs.postgresql
        run: kubectl port-forward svc/postgresql 5432:5432 &

      - name: Expose RabbitMQ service
        if: inputs.rabbitmq
        run: kubectl port-forward svc/rabbitmq 5672:5672 &

      - name: Install godotenv
        run: go install github.com/joho/godotenv/cmd/godotenv@latest

      - name: Install dependencies
        run: go mod download

      - name: Create .env file
        run: |
          cat <<EOT >> ${{ github.workspace }}/.env
          ${{ secrets.ENV_VARS }}
          EOT

      - name: Run tests
        run: make test
